server:
  port: 8100
  servlet:
    context-path: /api/royalseal
logging:
  level:
    root: WARN
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/royalseal?createDatabaseIfNotExist=true&userSSL=false&serverTimezone=UTC
    username: postgres
    password: S@pph4grace
    testWhileIdle: true
    validationQuery: SELECT 1
    driver-class-name: org.postgresql.Driver
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


      # Allows Hibernate to generate SQL optimized for a particular DBMS
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: grace.chidumaga@gmail.com
    password: sapph4god

    #other properties
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
#
#server:
#  port: 8085
#
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/royalseal?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
#    username: root
#    password: S@pph4grace
#
#
#  jpa:
#    #    show-sql: true
#    hibernate:
#      ddl-auto: update
#
#      # Allows Hibernate to generate SQL optimized for a particular DBMS
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: grace.chidumaga@gmail.com
#    password: S@pph4god
#
#    #other properties
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
#
##          use this links to allow access to your email... https://myaccount.google.com/security ... https://accounts.google.com/b/0/DisplayUnlockCaptcha

